# Generated by Django 5.1.1 on 2024-10-21 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('pais_origen', models.CharField(max_length=100)),
                ('estado_origen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jugador', models.CharField(max_length=200)),
                ('apellido_jugador', models.CharField(max_length=200)),
                ('numero_playera', models.IntegerField()),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha nacimieto')),
                ('posicion_campo', models.CharField(max_length=100)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.equipo')),
            ],
        ),
    ]
